# Application Name
spring.application.name=ROOM-SERVICE

# Server Configuration
server.port=8088

# Service squelette - pas de DB pour l'instant

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true
