# Server Configuration
server.port=0

# Application Name
spring.application.name=COURSE-SERVICE

# Service squelette - pas de DB pour l'instant

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Management Endpoints
management.endpoints.web.exposure.include=health,info
