# Configuration dev - MariaDB local
spring.datasource.url=jdbc:mariadb://localhost:3306/iusjcdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=iusjc
spring.datasource.password=iusjc2025
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

spring.sql.init.mode=never
