# Server Configuration
server.port=8888

# Application Name
spring.application.name=CONFIG-SERVER

# Config Server Git Configuration
spring.cloud.config.server.git.uri=https://github.com/Darlene-kitty/eduschedule-config
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Management Endpoints
management.endpoints.web.exposure.include=health,info
